apiVersion: batch/v1
kind: Job
metadata:
  name: test-skbn
  labels:
    name: test-skbn
    app: test-skbn
spec:
  template:
    metadata:
      labels:
        name: test-skbn
        app: test-skbn
      annotations:
        iam.amazonaws.com/role: test-dbbackup-operator 
    spec:
      restartPolicy: OnFailure
      serviceAccount: opsflow
      containers:
      - name: test-skbn
        image: nuvo/skbn:0.4.2
        resources:
          limits:
            memory: "4Gi"
            cpu: "4000m"
        command: ["skbn"]
        args: [
          "cp", 
          "--parallel", "15", 
          "--src", "k8s://invu-sre/cassandra-primary-r1-sts-0/cassandra/var/lib/cassandra/test.file", 
          "--dst", "s3://nuvo-dev-dbbackup/test.file"
        ]
        env:
        - name: AWS_REGION
          value: us-east-1
        imagePullPolicy: IfNotPresent
